services:
  project:
    container_name: finalprojectcontainer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    environment:
      - DATABASE_URL=sqlite:////code/db.sqlite3



